apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-route-vote
  namespace: votingapp
spec:
  parentRefs:
    - name: gw-votingapp
      namespace: gw-votingapp
  hostnames:
    - vote.conquerproject.io
  rules:
    - matches:
        - path:
            value: /
      backendRefs:
        - name: vote
          port: 80
